openapi: 3.0.3
info:
  title: User Registration API
  description: User Registration API for BeardTrust, LLC.
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    UserRegistration:
      description: User registration
      type: object
      required:
        - username
        - firstName
        - lastName
        - dateOfBirth
        - email
        - phone
        - role
        - password
      properties:
        username:
          description: The chosen username
          type: string
        firstName:
          description: The first name of the user
          type: string
        lastName:
          description: The last name of the user
          type: string
        dateOfBirth:
          description: The user's date of birth
          type: string
          format: date
        email:
          description: The user's email address
          type: string
        phone:
          description: The user's phone number
          type: string
        role:
          description: The user's role in the system
          type: string
        password:
          description: The user's password
          type: string
security:
  - BasicAuth: []
paths:
  /users:
    post:
      summary: Adds a user to the database
      operationId: registerUser
      requestBody:
        description: The user registration object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request.  Make sure user registration contains all required fields.